"""add games, favorites, recently_played, transaction.game_id

Revision ID: d0ff22600728
Revises: 3919442e428c
Create Date: 2026-08-26 01:13:53.033102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ff22600728'
down_revision: Union[str, Sequence[str], None] = '3919442e428c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('SLOTS', 'LIVE_CASINO', 'ROULETTE', 'BLACKJACK', 'POKER', 'JACKPOT', name='gamecategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_category'), 'games', ['category'], unique=False)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_favorites_user_game')
    )
    op.create_index(op.f('ix_favorites_game_id'), 'favorites', ['game_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('recently_played',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_recently_played_user_game')
    )
    op.create_index(op.f('ix_recently_played_game_id'), 'recently_played', ['game_id'], unique=False)
    op.create_index(op.f('ix_recently_played_user_id'), 'recently_played', ['user_id'], unique=False)
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_game_id'), ['game_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_game_id_games', 'games', ['game_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_game_id_games', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_game_id'))
        batch_op.drop_column('game_id')
    op.drop_index(op.f('ix_recently_played_user_id'), table_name='recently_played')
    op.drop_index(op.f('ix_recently_played_game_id'), table_name='recently_played')
    op.drop_table('recently_played')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_game_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_category'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
